# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_thing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='col_tag',
            field=models.CharField(default='tr', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='row_tag',
            field=models.CharField(default='tr', max_length=255),
            preserve_default=False,
        ),
    ]
