# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-11 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20170611_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='name',
            new_name='reference',
        ),
    ]
