# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20170611_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='col_tag',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='row_tag',
        ),
    ]
